# Generated by Django 2.2.7 on 2019-11-23 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='id_conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='id_viajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajero', to=settings.AUTH_USER_MODEL),
        ),
    ]
