# Generated by Django 2.2.7 on 2019-11-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_auto_20191123_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='alias',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
